{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-ui
    spec:
      containers:
      - name: ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: REGISTRY_URL
          value: "http://docker-registry.docker-registry.svc.cluster.local:5000"
        - name: DELETE_IMAGES
          value: "true"
        - name: REGISTRY_TITLE
          value: "My Platform Docker Registry"
        - name: NGINX_PROXY_PASS_URL
          value: "http://docker-registry.docker-registry.svc.cluster.local:5000"
        - name: SINGLE_REGISTRY
          value: "true"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}