{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}-ui
{{- end }}