apiVersion: v2
name: platform-ingress-nginx
description: NGINX Ingress Controller for the platform
type: application
version: 0.1.0
appVersion: "1.11.0"

dependencies:
  - name: ingress-nginx
    version: 4.11.3
    repository: https://kubernetes.github.io/ingress-nginx
