apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MehaGami/my-platform.git
    targetRevision: 0.1.0
    path: charts/docker-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
