apiVersion: v2
name: platform-argocd
description: Chart for ArgoCD
type: application
version: 0.1.0
appVersion: "2.13.0"

dependencies:
  - name: argo-cd
    version: 7.7.0
    repository: https://argoproj.github.io/argo-helm
